---
title: "Figure2"
author: "neurodevdisorder"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

These commands were used to generate different panels of Figure 2.

First, we will load all the packages required to perform this analysis
```{r setup, message = FALSE, warning=FALSE,include=TRUE}
library(ggplot2)
library(dplyr)
library(edgeR)
library(openxlsx)
library(ggrepel)
library(DBI)
library(org.Hs.eg.db)
library("pcaExplorer")
library(TxDb.Hsapiens.UCSC.hg38.knownGene)
library(rtracklayer)
library(ggbio)
library(clusterProfiler)
library(enrichplot)
library(ggridges)
library(karyoploteR)
library(tidyverse)
library(forcats)
library(pathview)
library(ComplexHeatmap)
library(circlize)
library(rsample)
library(magrittr)
library(superheat)
library(ggcorrplot)
```

#### Figure 2A

##### Hippocampus

```{r, echo = TRUE, warning=FALSE,include=TRUE}
hippo_rna_protein_overlap<-read.xlsx("data/gene_protein_correlation.xlsx",sheet=1)
require(stats)
reg<-lm(logFC_RNA ~ logFC_prot, data = hippo_rna_protein_overlap)
reg

ggplot(hippo_rna_protein_overlap, aes(x = logFC_prot, y = logFC_RNA)) +
  geom_point(aes(color =  factor(DE)), alpha=1, size=2) +
  scale_color_manual(values = c("#EF233C","#CED4DA","#05668D","#FB8500")) +
  xlab("Proteome logFC") + ylab("Transcriptome logFC")+
  theme_bw() +
  xlim(-5,5)+
  ylim(-2,4)+
  theme(text=element_text(size=18),axis.text.x = element_text(color = "black"),axis.text.y = element_text(color="black"),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank())+ 
  geom_abline(intercept = -0.001667, slope = 0.099842, color="black", linetype="dashed", size=0.5)

cor(hippo_rna_protein_overlap$logFC_prot,hippo_rna_protein_overlap$logFC_RNA,method = "pearson")
```

##### Cortex
```{r, echo = TRUE, warning=FALSE,include=TRUE}
cortex_rna_protein_overlap<-read.xlsx("data/gene_protein_correlation.xlsx",sheet=2)
require(stats)
reg<-lm(logFC_RNA ~ logFC_prot, data = cortex_rna_protein_overlap)
reg

ggplot(cortex_rna_protein_overlap, aes(x = logFC_prot, y = logFC_RNA)) +
  geom_point(aes(color =  factor(DE)), alpha=1, size=2) +
  scale_color_manual(values = c("#EF233C","#CED4DA","#05668D","#FB8500")) +
  xlab("Proteome logFC") + ylab("Transcriptome logFC")+
  theme_bw() +
  xlim(-5,5)+
  ylim(-2,4)+
  theme(text=element_text(size=18),axis.text.x = element_text(color = "black"),axis.text.y = element_text(color="black"),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank())+ 
  geom_abline(intercept = -0.1244, slope = 0.1551, color="black", linetype="dashed", size=0.5)

cor(cortex_rna_protein_overlap$logFC_prot,cortex_rna_protein_overlap$logFC_RNA,method = "pearson")
```

#### Figure 2B

```{r, echo = TRUE, warning=FALSE,include=TRUE}
hippo_cortex_RNA_protein_corr<- read.table(file= "data/hippo_cortex_RNA_protein.txt", header=T, row.names=1)
corr <- round(cor(hippo_cortex_RNA_protein_corr), 1)
ggcorrplot(corr, hc.order = TRUE, 
           type = "lower", 
           lab = TRUE, 
           lab_size = 3, 
           method="circle", 
           colors = c( "springgreen3","white", "tomato2"), 
           lab_col = "black",
           outline.color = "black",
           title="Correlogram of Hippocampus and Cortex for RNA & Protein", 
           ggtheme=theme_bw)+
           theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),panel.background = element_blank())
```
           
Figure 2C is prepared with the help of venny2.1 (https://bioinfogp.cnb.csic.es/tools/venny/)

#### Figure 2D

##### Hippocampus

```{r, echo = TRUE, warning=FALSE,include=TRUE}
hippo_rna_protein_overlap_DE<-read.xlsx("data/gene_protein_correlation.xlsx",sheet=3)
reg<-lm(logFC_RNA ~ logFC_prot, data = hippo_rna_protein_overlap_DE)
reg

ggplot(hippo_rna_protein_overlap_DE, aes(x = logFC_prot, y = logFC_RNA)) +
  geom_point(aes(color =  factor(direction)), alpha=1, size=2) +
  scale_color_manual(values = c("#FFB703","#2A9D8F")) +
  xlab("Proteome logFC") + ylab("Transcriptome logFC")+
  theme_bw() +
  xlim(-5,5)+
  ylim(-2,4)+
  theme(text=element_text(size=18),axis.text.x = element_text(color = "black"),axis.text.y = element_text(color="black"),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank())+ 
  geom_hline(yintercept=0, linetype="dashed", color = "black")+
  geom_vline(xintercept = 0,linetype="dashed",color="black")
```

##### Cortex

```{r, echo = TRUE, warning=FALSE,include=TRUE}
cortex_rna_protein_overlap_DE<-read.xlsx("data/gene_protein_correlation.xlsx",sheet=4)
reg<-lm(logFC_RNA ~ logFC_prot, data = cortex_rna_protein_overlap_DE)
reg

ggplot(cortex_rna_protein_overlap_DE, aes(x = logFC_prot, y = logFC_RNA)) +
  geom_point(aes(color =  factor(direction)), alpha=1, size=2) +
  scale_color_manual(values = c("#FFB703","#2A9D8F")) +
  xlab("Proteome logFC") + ylab("Transcriptome logFC")+
  theme_bw() +
  xlim(-5,5)+
  ylim(-2,4)+
  theme(text=element_text(size=18),axis.text.x = element_text(color = "black"),axis.text.y = element_text(color="black"),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank())+ 
  geom_hline(yintercept=0, linetype="dashed", color = "black")+
  geom_vline(xintercept = 0,linetype="dashed",color="black")
```

#### Figure 2E

```{r, echo = TRUE, warning=FALSE,include=TRUE}
hippo_cortex_RNA_protein_DAVID_BP<-read.xlsx("data/gene_protein_correlation.xlsx",sheet=6)
row.names(hippo_cortex_RNA_protein_DAVID_BP)<-hippo_cortex_RNA_protein_DAVID_BP$Sample

hippo_cortex_RNA_protein_DAVID_BP_filt<-as.data.frame(hippo_cortex_RNA_protein_DAVID_BP[,-c(1)])
f2 = colorRamp2(seq(min(hippo_cortex_RNA_protein_DAVID_BP_filt), max(hippo_cortex_RNA_protein_DAVID_BP_filt), length = 3), c("#EEEEEE","blue", "red"), space = "RGB")

Heatmap(hippo_cortex_RNA_protein_DAVID_BP_filt, col = f2, cluster_rows = FALSE,cluster_columns = FALSE,
        row_order = order(as.numeric(gsub("row", "", rownames(hippo_cortex_RNA_protein_DAVID_BP_filt)))), 
        column_order = order(as.numeric(gsub("column", "", colnames(hippo_cortex_RNA_protein_DAVID_BP_filt)))),
        row_names_gp = gpar(fontsize = 6),column_names_gp = gpar(fontsize=6),
        column_names_centered = TRUE)
```



