---
title: "GABA_AMPA"
author: "neurodevdisorder"
date: "2022-07-15"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

Here, we see the expression of GABA and AMPA receptor subunits in both hippocampus and cortex between the DS and control individuals.

```{r setup, message = FALSE, warning=FALSE,include=FALSE}
library(ggplot2)
library(openxlsx)
library(ggrepel)
library(ggplot2)
library(dplyr)
```


```{r, echo=FALSE}
GABA_family<-read.xlsx("data/GABA_AMPA_family.xlsx",sheet=1)
GABA_family$Group <- factor(GABA_family$Group,levels = c("Hippocampus Ctrl", "Hippocampus DS", "Cortex Ctrl", "Cortex DS"))
GABA_01 <- ggplot(GABA_family, aes(Symbol, CPM))+
  geom_boxplot(aes(color=factor(Group))) +
  scale_color_manual(values = c("#3B429F","#AA7DCE","#A8577E","#F4A5AE")) +
  theme(axis.text.x = element_text(angle=65, vjust=0.6,color ="black"),text=element_text(size=10),axis.text.y = element_text(color="black")) +
  labs(title="Brain gene expression of GABA receptor subunits",
       subtitle="in Human DS Hippocampus and Cortex",
       x="GABA subunits",
       y="Counts per Million")+
  labs(color="Brain Region")+theme_bw()
```

```{r, echo=FALSE, fig.dim = c(12, 8)}
GABA_01
```


```{r, echo=FALSE}
AMPA_family<-read.xlsx("data/GABA_AMPA_family.xlsx",sheet=2)
AMPA_family$Group <- factor(AMPA_family$Group,levels = c("Hippocampus Ctrl", "Hippocampus DS", "Cortex Ctrl", "Cortex DS"))
AMPA_01 <- ggplot(AMPA_family, aes(Symbol, CPM))+
  geom_boxplot(aes(color=factor(Group))) +
  scale_color_manual(values = c("#3B429F","#AA7DCE","#A8577E","#F4A5AE")) +
  theme(axis.text.x = element_text(angle=65, vjust=0.6)) +
  labs(title="Brain gene expression of AMPA receptor subunits",
       subtitle="in Human DS Hippocampus and Cortex",
       x="AMPA subunits",
       y="Counts per Million")+
  labs(color="Brain Region")+theme_bw()
```


```{r, echo=FALSE,fig.dim = c(8, 6)}
AMPA_01
```

